//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoGame
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Animal
    {
        public int AnimalId { get; set; }

        [Required]
        public string SoundAnimal { get; set; }
        [Required]
        public string DescAnimal { get; set; }
        [Required]
        public string ImgAnimal { get; set; }
        [Required]
        public string NameAnimal { get; set; }
    
        public virtual Ecosystem Ecosystem { get; set; }
    }
}
