//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoGame
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcoGameModelContainer : DbContext
    {
        public EcoGameModelContainer()
            : base("name=EcoGameModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Profile> ProfileSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Animal> AnimalSet { get; set; }
        public virtual DbSet<Ecosystem> EcosystemSet { get; set; }

        public System.Data.Entity.DbSet<EcoGame.ViewModels.AnimalVM> AnimalVMs { get; set; }
    }
}
