//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ecosystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ecosystem()
        {
            this.Animals = new HashSet<Animal>();
        }
    
        public int EcosystemId { get; set; }
        public string ImgEcosystem { get; set; }
        public string DescEcosystem { get; set; }
        public string NameEcosystem { get; set; }
        public string RegEcosystem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal> Animals { get; set; }
    }
}
